In [1]:
#加载必要的库
import os
import gc
from glob import glob
from pathlib import Path
from datetime import datetime
import re

import numpy as np
import pandas as pd
import polars as pl

import matplotlib.pyplot as plt
import seaborn as sns

import joblib
import lightgbm as lgb
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import VotingClassifier
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
pd.set_option('display.max_columns', None)

ModuleNotFoundError: No module named 'lightgbm'

In [2]:
#数据位置设置
class root:
    train = Path("D:/home-credit-credit-risk-model-stability/parquet_files/train")
    test = Path("D:/home-credit-credit-risk-model-stability/parquet_files/test")

In [3]:
#观察各个特征的意义
if __name__ == '__main__':
    feature_definitions_df = pd.read_csv('D:/home-credit-credit-risk-model-stability/feature_definitions.csv')
    display(feature_definitions_df)
    pd.reset_option("display.max_rows", 0)

Variable  \
0              actualdpd_943P   
1     actualdpdtolerance_344P   
2        addres_district_368M   
3            addres_role_871L   
4             addres_zip_823M   
..                        ...   
460  totinstallast1m_4525188A   
461        twobodfilling_608L   
462                  type_25L   
463            typesuite_864L   
464           validfrom_1069D   

                                           Description  
0    Days Past Due (DPD) of previous contract (actu...  
1                        DPD of client with tolerance.  
2                    District of the person's address.  
3                            Role of person's address.  
4                             Zip code of the address.  
..                                                 ...  
460  Total amount of monthly instalments paid in th...  
461                       Type of application process.  
462                          Contact type of a person.  
463  Persons accompanying the client during the loa...  
464      Date since the client has an active campaign.  

[465 rows x 2 columns]

In [4]:
#在data_base中每个id对应着一个目标值，有借款的日期和月份，
data_base=pl.read_parquet(root.train/'train_base.parquet')
data_base

shape: (1_526_659, 5)
┌─────────┬───────────────┬────────┬──────────┬────────┐
│ case_id ┆ date_decision ┆ MONTH  ┆ WEEK_NUM ┆ target │
│ ---     ┆ ---           ┆ ---    ┆ ---      ┆ ---    │
│ i64     ┆ str           ┆ i64    ┆ i64      ┆ i64    │
╞═════════╪═══════════════╪════════╪══════════╪════════╡
│ 0       ┆ 2019-01-03    ┆ 201901 ┆ 0        ┆ 0      │
│ 1       ┆ 2019-01-03    ┆ 201901 ┆ 0        ┆ 0      │
│ 2       ┆ 2019-01-04    ┆ 201901 ┆ 0        ┆ 0      │
│ 3       ┆ 2019-01-03    ┆ 201901 ┆ 0        ┆ 0      │
│ …       ┆ …             ┆ …      ┆ …        ┆ …      │
│ 2703451 ┆ 2020-10-05    ┆ 202010 ┆ 91       ┆ 0      │
│ 2703452 ┆ 2020-10-05    ┆ 202010 ┆ 91       ┆ 0      │
│ 2703453 ┆ 2020-10-05    ┆ 202010 ┆ 91       ┆ 0      │
│ 2703454 ┆ 2020-10-05    ┆ 202010 ┆ 91       ┆ 0      │
└─────────┴───────────────┴────────┴──────────┴────────┘

In [5]:
#观察数据发现有很多相同的id，每个id都对应着很多条数据，那么我们应该从其中保留或者找到最有价值的一条数据为下一步多表连接做准备（因为在train_base中只有每一个id对应着一个目标值）
data=pl.read_parquet(root.train/'train_credit_bureau_a_1_0.parquet')
data

shape: (4_108_212, 79)
┌─────────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ case_id ┆ annualeffe ┆ annualeffe ┆ classifica ┆ … ┆ totaldebto ┆ totaldebto ┆ totaloutst ┆ totaloutst │
│ ---     ┆ ctiverate_ ┆ ctiverate_ ┆ tionofcont ┆   ┆ verduevalu ┆ verduevalu ┆ anddebtval ┆ anddebtval │
│ i64     ┆ 199L       ┆ 63L        ┆ r_13M      ┆   ┆ e_178A     ┆ e_718A     ┆ ue_39A     ┆ ue_668A    │
│         ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│         ┆ f64        ┆ f64        ┆ str        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 388     ┆ null       ┆ null       ┆ 4408ff0f   ┆ … ┆ 0.0        ┆ 0.0        ┆ 374419.5   ┆ 0.0        │
│ 388     ┆ null       ┆ null       ┆ ea6782cc   ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ 388     ┆ null       ┆ null       ┆ a55475b1   ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ 388     ┆ null       ┆ null       ┆ a55475b1   ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ …       ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2588481 ┆ null       ┆ null       ┆ a55475b1   ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ 2588481 ┆ null       ┆ null       ┆ a55475b1   ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ 2588481 ┆ null       ┆ null       ┆ a55475b1   ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ 2588481 ┆ null       ┆ null       ┆ a55475b1   ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
└─────────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [6]:
#定义类preprocessing，并定义相关静态函数
#根据数据的类型将特征数据类型改为整型，浮点型和日期型与字符串型
#根据列名最后的字母来进行判断
class preprocessing:
    #改变特征的数据类型
    @staticmethod
    def set_table_dtypes(df):
        for col in df.columns:
            if col in ["case_id", "WEEK_NUM", "num_group1", "num_group2"]:
                df = df.with_columns(pl.col(col).cast(pl.Int64))
            elif col in ["date_decision"]:
                df = df.with_columns(pl.col(col).str.strptime(pl.Date, "%Y-%m-%d"))
            elif col[-1] in ("P", "A"):
                df = df.with_columns(pl.col(col).cast(pl.Float64))
            elif col[-1] in ("M"):
                df = df.with_columns(pl.col(col).cast(pl.Utf8))
            elif col[-1] in ("D"):
                df = df.with_columns(pl.col(col).str.strptime(pl.Date, "%Y-%m-%d"))            

        return df
    #将日期转换为距离D特征的时间，进行初步特征工程
    @staticmethod
    def handle_dates(df):
        for col in df.columns:
            if col[-1] in ("D"):
                df = df.with_columns((pl.col(col) - pl.col("date_decision")).dt.days())
                
        df = df.drop("date_decision", "MONTH")

        return df
    
    #特征筛选函数，缺失率大于95%或者是除了字符串和日期id等特征以外的特类别太少或者太多的的特征移除
    @staticmethod
    def filter_cols(df):
        for col in df.columns:
            if col not in ["target", "case_id", "WEEK_NUM"]:
                isnull_per = df[col].is_null().mean()

                if isnull_per > 0.95:
                    df = df.drop(col)
    
        for col in df.columns:
            if (col not in ["target", "case_id", "WEEK_NUM"]) & (df[col].dtype == pl.Utf8):
                freq = df[col].n_unique()

                if (freq == 1) | (freq > 200):
                    df = df.drop(col)

        return df

In [7]:
#因为观察上面的数据发现每个id都对应着很多条数据，所以在此要把数据进行处理。
#根据每个特征不同的数据类型进行分别处理
#为了代码保持简洁，创建Aggregator类与多个静态方法进行处理
#特征不同后缀对应的数据类型不一样，如后缀为D的特征为日期型特征，后缀为P和A的特征为连续数值型，后缀为M的为编码字符串型数据
#在这里使用polars的表达式，可以实现并行操作，并且polars的表达式本质上还是可迭代对象，可以很方便的进行分组的每个列进行操作
class Aggregator:
    num_aggregators = [pl.max, pl.min, pl.first, pl.last, pl.mean]#对于数值变量我们就使用分组中的最大值最小值第一个值和最后一个值还有平均值作为这个id的特征
    str_group_aggregators = [pl.max, pl.min, pl.first, pl.last]
    group_aggregators=[pl.max, pl.min, pl.first, pl.last]

    
    @staticmethod
    def num_expr(df):
        cols = [col for col in df.columns if col[-1] in ("P", "A")]
        expr_all = []
        for method in Aggregator.num_aggregators:
            expr = [method(col).alias(f"{method.__name__}_{col}") for col in cols]
            expr_all += expr

        return expr_all

    @staticmethod
    def date_expr(df):
        cols = [col for col in df.columns if col[-1] in ("D")]
        expr_all = []
        for method in Aggregator.num_aggregators:
            expr = [method(col).alias(f"{method.__name__}_{col}") for col in cols]  
            expr_all += expr

        return expr_all

    @staticmethod
    def str_expr(df):
        cols = [col for col in df.columns if col[-1] in ("M")]
        
        expr_all = []
        for method in Aggregator.str_group_aggregators:
            expr = [method(col).alias(f"{method.__name__}_{col}") for col in cols]  
            expr_all += expr
        #在这里我们还是用所有分组中的出现最多的编码（众数）作为这个id的特征
        expr_mode = [
            pl.col(col)
            .drop_nulls()
            .mode()
            .first()
            .alias(f"mode_{col}")
            for col in cols
        ]
        return expr_all + expr_mode

    @staticmethod
    def other_expr(df):
        cols = [col for col in df.columns if col[-1] in ("T", "L")]
        
        expr_all = []
        for method in Aggregator.group_aggregators:
            expr = [method(col).alias(f"{method.__name__}_{col}") for col in cols]  
            expr_all += expr
        return expr_all
    
    @staticmethod
    def count_expr(df):
        cols = [col for col in df.columns if "num_group" in col]
        expr_all = []
        for method in Aggregator.str_group_aggregators:
            expr = [method(col).alias(f"{method.__name__}_{col}") for col in cols]  
            expr_all += expr
        return expr_all

    @staticmethod
    def get_exprs(df):
        exprs = Aggregator.num_expr(df)+Aggregator.date_expr(df)+Aggregator.str_expr(df)+Aggregator.other_expr(df)+Aggregator.count_expr(df)
        return exprs

In [8]:
#数据读取
def read_file(path, depth=None):
    df = pl.read_parquet(path)
    df = df.pipe(preprocessing.set_table_dtypes)
    
    if depth in [1, 2]:
        df = df.groupby("case_id").agg(Aggregator.get_exprs(df))
    
    return df

def read_files(some_path, depth=None):
    chunks = []
    for path in glob(str(some_path)):
        chunks.append(pl.read_parquet(path).pipe(preprocessing.set_table_dtypes))
        
    df = pl.concat(chunks, how="vertical_relaxed")
    if depth in [1, 2]:
        df = df.groupby("case_id").agg(Aggregator.get_exprs(df))
    
    return df

In [9]:
#特征工程，将借款日期准换成第几周和第几天，将所有读取的数据表格全部连接起来，
def feature_eng(df_base, data0,data1, data2):
    df_base = (
        df_base
        .with_columns(
            month_decision = pl.col("date_decision").dt.month(),
            weekday_decision = pl.col("date_decision").dt.weekday()
        )
    )
        
    for i, df in enumerate(data0 + data1 + data2):
        df_base = df_base.join(df, how="left", on="case_id", suffix=f"_{i}")
        
    df_base = df_base.pipe(preprocessing.handle_dates)
    
    return df_base

In [10]:
#转换函数，将polars文件转换为pandas方便之后放回模型中处理
def to_pandas(df_data, cat_cols=None):
    df_data = df_data.to_pandas()
    
    if cat_cols is None:
        cat_cols = list(df_data.select_dtypes("object").columns)
    
    df_data[cat_cols] = df_data[cat_cols].astype("category")
    
    return df_data

In [11]:
#前面的准备工作已经弄完，预处理类，读取数据函数，聚合特征信息提取类，和特征工程函数已经准备好，之后可以放到同一个函数中处理训练集和测试集
def prepare(data_dir, cat_cols=None, mode="train", display_store=False, train_cols=[]):
    #通过之前read_file进行数据的读取
    print("传入数据.")
    data_store = {
        "df_base": read_file(data_dir / f"{mode}_base.parquet"),
        "data0": [
            read_file(data_dir / f"{mode}_static_cb_0.parquet"),
            read_files(data_dir / f"{mode}_static_0_*.parquet")
        ],
        "data1": [
            read_files(data_dir / f"{mode}_applprev_1_*.parquet", 1),
            read_file(data_dir / f"{mode}_tax_registry_a_1.parquet", 1),
            read_file(data_dir / f"{mode}_tax_registry_b_1.parquet", 1),
            read_file(data_dir / f"{mode}_tax_registry_c_1.parquet", 1),
            read_file(data_dir / f"{mode}_credit_bureau_b_1.parquet", 1),
            read_file(data_dir / f"{mode}_other_1.parquet", 1),
            read_file(data_dir / f"{mode}_person_1.parquet", 1),
            read_file(data_dir / f"{mode}_deposit_1.parquet", 1),
            read_file(data_dir / f"{mode}_debitcard_1.parquet", 1)
        ],
        "data2": [
            read_file(data_dir / f"{mode}_credit_bureau_b_2.parquet", 2)
        ]
    }
    if display_store:
        display(data_store)
    
    print("正在特征工程")
    feats_df = feature_eng(**data_store)
    print("特征df形状:\t", feats_df.shape)
    
    del data_store
    gc.collect()
    
    print("筛选特征")
    if mode == "train":
        feats_df = feats_df.pipe(preprocessing.filter_cols)
    else:
        train_cols = feats_df.columns if len(train_cols) == 0 else train_cols
        feats_df = feats_df.select([col for col in train_cols if col != "target"])
    print("特征df形状:\t", feats_df.shape)
    
    print("转换成pandas")
    feats_df = to_pandas(feats_df, cat_cols)
    return feats_df

In [12]:
if __name__ == '__main__':
    train=prepare(root.train)

传入数据.
正在特征工程
特征df形状:	 (1526659, 927)
筛选特征
特征df形状:	 (1526659, 502)
转换成pandas


In [13]:
#根据每个定量特征的取值范围优化内存

def reduce_memory_usage(df, float16_as32=True):

    start = df.memory_usage().sum() / 1024**2
    print('df所占内存为 {:.2f} MB'.format(start))
    
    for col in df.columns:
        col_type = df[col].dtype
        if str(col_type)=="category":
            continue
        
        if col_type != object:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    if float16_as32:
                        df[col] = df[col].astype(np.float32)
                    else:
                        df[col] = df[col].astype(np.float16)                    
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)
        else:
            df[col] = df[col].astype('category')
    end = df.memory_usage().sum() / 1024**2
    print('df所占内存现在为: {:.2f} MB'.format(end))
    print('降低了{:.1f}%'.format(100 * (start - end) / start))
    
    return df

In [14]:
train=reduce_memory_usage(train)

df所占内存为 4420.28 MB
df所占内存现在为: 2287.33 MB
降低了48.3%


In [16]:
train.head(20)

case_id  WEEK_NUM  target  month_decision  weekday_decision  \
0         0         0       0             1.0               4.0   
1         1         0       0             1.0               4.0   
2         2         0       0             1.0               5.0   
3         3         0       0             1.0               4.0   
4         4         0       1             1.0               5.0   
5         5         0       0             1.0               3.0   
6         6         0       0             1.0               4.0   
7         7         0       0             1.0               4.0   
8         8         0       0             1.0               4.0   
9         9         0       0             1.0               4.0   
10       10         0       0             1.0               4.0   
11       11         0       0             1.0               4.0   
12       12         0       0             1.0               4.0   
13       13         0       0             1.0               4.0   
14       14         0       0             1.0               4.0   
15       15         0       0             1.0               4.0   
16       16         0       0             1.0               4.0   
17       17         0       0             1.0               4.0   
18       18         0       0             1.0               4.0   
19       19         0       0             1.0               4.0   

    assignmentdate_238D  assignmentdate_4527235D  birthdate_574D  \
0                   NaN                      NaN             NaN   
1                   NaN                      NaN             NaN   
2                   NaN                      NaN             NaN   
3                   NaN                      NaN             NaN   
4                   NaN                      NaN             NaN   
5                   NaN                      NaN             NaN   
6                   NaN                      NaN             NaN   
7                   NaN                      NaN             NaN   
8                   NaN                      NaN             NaN   
9                   NaN                      NaN             NaN   
10                  NaN                      NaN             NaN   
11                  NaN                      NaN             NaN   
12                  NaN                      NaN             NaN   
13                  NaN                      NaN             NaN   
14                  NaN                      NaN             NaN   
15                  NaN                      NaN             NaN   
16                  NaN                      NaN             NaN   
17                  NaN                      NaN             NaN   
18                  NaN                      NaN             NaN   
19                  NaN                      NaN             NaN   

    contractssum_5085716L  dateofbirth_337D  days120_123L  days180_256L  \
0                     NaN               NaN           NaN           NaN   
1                     NaN               NaN           NaN           NaN   
2                     NaN               NaN           NaN           NaN   
3                     NaN               NaN           NaN           NaN   
4                     NaN               NaN           NaN           NaN   
5                     NaN               NaN           NaN           NaN   
6                     NaN               NaN           NaN           NaN   
7                     NaN               NaN           NaN           NaN   
8                     NaN               NaN           NaN           NaN   
9                     NaN               NaN           NaN           NaN   
10                    NaN               NaN           NaN           NaN   
11                    NaN               NaN           NaN           NaN   
12                    NaN               NaN           NaN           NaN   
13                    NaN               NaN           NaN           NaN   
14                    NaN               Na

In [4]:
from sklearn.model_selection import StratifiedGroupKFold

In [5]:
X=np.ones([12,2])
y=np.array([1,1,1,0,0,0,0,1,1,1,0,1])
group=[1,1,1,1,2,2,2,2,3,3,3,3]
cv=StratifiedGroupKFold(n_splits=5, shuffle=False)

In [9]:
for i,j in cv.split(X,y,group):
    print(i,j,type(i))

[ 4  5  6  7  8  9 10 11] [0 1 2 3] <class 'numpy.ndarray'>
[ 0  1  2  3  8  9 10 11] [4 5 6 7] <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7] [ 8  9 10 11] <class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11] [] <class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11] [] <class 'numpy.ndarray'>


In [ ]:
import os
import gc
from glob import glob
from pathlib import Path
from datetime import datetime
import numpy as np
import pandas as pd
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [ ]:
data_nb.Aggregator.group_aggregators = [pl.n_unique]
train_df = data_nb.prepare_df(data_nb.CFG.train_dir)
cat_cols = list(train_df.select_dtypes("category").columns)
display(train_df)

In [ ]:
test_df = data_nb.prepare_df(data_nb.CFG.test_dir, cat_cols=cat_cols, mode="test", train_cols=train_df.columns)
display(test_df)

In [ ]:
def gini_stability(base, score_col="score", w_fallingrate=88.0, w_resstd=-0.5):
    gini_in_time = base.loc[:, ["WEEK_NUM", "target", score_col]]\
        .sort_values("WEEK_NUM")\
        .groupby("WEEK_NUM")[["target", score_col]]\
        .apply(lambda x: 2*roc_auc_score(x["target"], x[score_col])-1).tolist()
    
    x = np.arange(len(gini_in_time))
    y = gini_in_time
    a, b = np.polyfit(x, y, 1)
    y_hat = a*x + b
    residuals = y - y_hat
    res_std = np.std(residuals)
    avg_gini = np.mean(gini_in_time)
    return avg_gini + w_fallingrate * min(0, a) + w_resstd * res_std

In [ ]:
X = train_df.drop(columns=["target", "case_id", "WEEK_NUM"] + drop_cols)
print("X shape: ", X.shape)
y = train_df["target"]
weeks = train_df["WEEK_NUM"]

cv = StratifiedGroupKFold(n_splits=5, shuffle=False)

params = {
    "boosting_type": "gbdt",
    "objective": "binary",
    "metric": "auc",
    "max_depth": 8,
    "max_bin": 255,
    "learning_rate": 0.05,
    "n_estimators": 1000,
    "colsample_bytree": 0.8, 
    "colsample_bynode": 0.8,
    "verbose": -1,
    "random_state": 42,
    "device": "gpu",
}

fitted_models = []
oof_pred = np.zeros(X.shape[0])

for idx_train, idx_valid in cv.split(X, y, groups=weeks):
    X_train, y_train = X.iloc[idx_train], y.iloc[idx_train]
    X_valid, y_valid = X.iloc[idx_valid], y.iloc[idx_valid]

    model = lgb.LGBMClassifier(**params)
    model.fit(
        X_train, y_train,
        eval_set=[(X_valid, y_valid)],
        callbacks=[lgb.log_evaluation(100), lgb.early_stopping(100)]
    )
    fitted_models.append(model)
    val_pred = model.predict_proba(X_valid)[:, 1]
    oof_pred[idx_valid] = val_pred
    gc.collect()